// Generated by scripts/sync-deployment.mjs from the deployment handoff. Do not edit by hand.
// Build-time facts that are not part of imd-deployment.json: the Uniswap v4 pool key parameters
// of the launch token's pool (currency1 is the token, whose address the app reads from the
// runtime manifest) and the block at which the contracts were deployed, used as the lower bound
// for event log scans. The app double-checks the block against chain code before using it.
export const POOL = {
  fee: 3000,
  tickSpacing: 60,
  pairedCurrency: '0x0000000000000000000000000000000000000000',
  hooks: '0x0000000000000000000000000000000000000000',
  initialPrice: '79228162514264337593543950336',
} as const;

export const START_BLOCK = 11805514n;
